---
- hosts: "{{ hostname }}"
  become: true

- name: Configure device DNS
  ansible.builtin.import_playbook: modules/configure_dns.yml

- name: Update system
  ansible.builtin.import_playbook: modules/update_system.yml

- name: Install Wazuh on the device
  ansible.builtin.import_playbook: modules/install_wazuh.yml