---
- name: Set the Internal DNS server
  when: inventory_hostname in groups['Endpoints']
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNS='
    line: DNS=192.168.1.48

- name: Set the Hosting DNS server
  when: inventory_hostname in groups['Servers']
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNS='
    line: DNS=192.168.2.88

- name: Restart systemd-resolved service
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
    daemon_reload: true